      - name: Commit project
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git restore --source=HEAD -- .github/workflows/extract.yml
          git add -A
          git commit -m "Update Chauffeur application" || exit 0
          git push
